services:
  app:
    build: .
    restart: always
    environment:
      - PORT=3000
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dx-website.rule=Host(`dx.rax0.de`)"
      - "traefik.http.routers.dx-website.entrypoints=websecure"
      - "traefik.http.routers.dx-website.tls.certresolver=myresolver"
      - "traefik.http.services.dx-website.loadbalancer.server.port=3000"

networks:
  web:
    external: true
